apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitops
  labels:
    app.kubernetes.io/managed-by: fab-rig
spec:
  destination:
    name: ''
    namespace: openshift-gitops
    server: 'https://kubernetes.default.svc'
  source:
    path: manifests/27-gitops
    repoURL: https://github.com/bbenshab/Infrabric-deployer.git
    targetRevision: main
  sources: []
  project: default
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
      allowEmpty: false
    syncOptions:
      - ServerSideApply=true
    retry:
      limit: 8
      backoff:
        duration: 5s
        maxDuration: 5m0s
        factor: 2
